Loto.pageHeader();Loto.protectPage();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active');});
const lotoName=document.getElementById('lotoName'),lotoDate=document.getElementById('lotoDate'),prevalidate=document.getElementById('prevalidate'),showLots=document.getElementById('showLots'),bingoEnabled=document.getElementById('bingoEnabled'),showBingo=document.getElementById('showBingo'),partiesList=document.getElementById('partiesList'),partieCount=document.getElementById('partieCount'),simulationEnabled=document.getElementById('simulationEnabled'),simulationSeconds=document.getElementById('simulationSeconds');
const prizeTypes=['Ligne','Deux lignes','Carton plein'];
function defaultPrize(i,label=''){return {type:prizeTypes[i],label,enabled:true};}
function defaultPartie(i){return {name:'Partie '+(i+1),prizes:[defaultPrize(0),defaultPrize(1),defaultPrize(2)]};}
function drawParties(){const s=Loto.state();const parties=s.program?.parties||[];partieCount.value=parties.length||Number(partieCount.value||6);partiesList.innerHTML=parties.map((p,i)=>`<div class="card partie-edit"><h3>Partie ${i+1}</h3><label>Nom<input data-p="${i}" data-f="name" value="${p.name||('Partie '+(i+1))}"></label><div class="three-cols">${prizeTypes.map((t,pi)=>`<div><label><input data-p="${i}" data-prize-enabled="${pi}" type="checkbox" ${p.prizes?.[pi]?.enabled===false?'':'checked'} style="width:auto"> ${t}</label><input data-p="${i}" data-prize="${pi}" placeholder="Lot ${t.toLowerCase()}" value="${p.prizes?.[pi]?.label||''}"></div>`).join('')}</div></div>`).join('')||'<p>Aucune partie.</p>';}
function readProgram(){const s=Loto.state();const parties=JSON.parse(JSON.stringify(s.program?.parties||[]));partiesList.querySelectorAll('input[data-p]').forEach(inp=>{const p=Number(inp.dataset.p);parties[p] ||= defaultPartie(p);parties[p].prizes ||= [defaultPrize(0),defaultPrize(1),defaultPrize(2)];if(inp.dataset.f==='name')parties[p].name=inp.value;if(inp.dataset.prize){const pi=Number(inp.dataset.prize);parties[p].prizes[pi] ||= defaultPrize(pi);parties[p].prizes[pi].label=inp.value;}if(inp.dataset.prizeEnabled){const pi=Number(inp.dataset.prizeEnabled);parties[p].prizes[pi] ||= defaultPrize(pi);parties[p].prizes[pi].enabled=inp.checked;}});return {title:lotoName.value||Loto.state().program?.title||'Loto',date:lotoDate.value||'',parties};}
document.getElementById('saveGeneral').onclick=()=>Loto.save({lotoName:lotoName.value||'LOTO SDS',program:{...(Loto.state().program||{}),title:lotoName.value||'Loto',date:lotoDate.value||''},options:{...Loto.state().options,prevalidateSeconds:Number(prevalidate.value||6)}});
document.getElementById('generateParties').onclick=()=>{let program=readProgram();const target=Math.max(1,Number(partieCount.value||1));while(program.parties.length<target)program.parties.push(defaultPartie(program.parties.length));program.parties=program.parties.slice(0,target);Loto.save({program});};
document.getElementById('saveProgram').onclick=()=>Loto.save({program:readProgram(),currentPartieIndex:0,currentPrizeIndex:0,options:{...Loto.state().options,showLots:showLots.checked}});
document.getElementById('saveBingo').onclick=()=>Loto.save({options:{...Loto.state().options,bingoEnabled:bingoEnabled.checked,showBingo:showBingo.checked}});
document.getElementById('saveSimulation').onclick=()=>Loto.save({simulation:{enabled:simulationEnabled.checked,seconds:Number(simulationSeconds.value||10)}});
document.getElementById('testCardBtn').onclick=async()=>{const n=document.getElementById('testCard').value;const c=await Loto.fetchCard?.(n);document.getElementById('testCardResult').textContent=c?JSON.stringify(c,null,2):'Carton introuvable';};
Loto.onChange(s=>{Loto.pageHeader();lotoName.value=s.lotoName||'LOTO SDS';lotoDate.value=s.program?.date||'';prevalidate.value=s.options?.prevalidateSeconds||6;showLots.checked=!!s.options?.showLots;bingoEnabled.checked=!!s.options?.bingoEnabled;showBingo.checked=!!s.options?.showBingo;simulationEnabled.checked=!!s.simulation?.enabled;simulationSeconds.value=s.simulation?.seconds||10;drawParties();});
Loto.ensureSession();
