Loto.pageHeader();Loto.protectPage();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active');});
const lotoName=document.getElementById('lotoName'),prevalidate=document.getElementById('prevalidate'),showLots=document.getElementById('showLots'),bingoEnabled=document.getElementById('bingoEnabled'),showBingo=document.getElementById('showBingo'),partiesList=document.getElementById('partiesList');
function drawParties(){const s=Loto.state();const parties=s.program?.parties||[];partiesList.innerHTML=parties.map((p,i)=>`<div class="card" style="margin:10px 0"><h3>Partie ${i+1}</h3><label>Nom<input data-p="${i}" data-f="name" value="${p.name||''}"></label><div class="two-cols"><label>Ligne<input data-p="${i}" data-prize="0" value="${p.prizes?.[0]?.label||''}"></label><label>Deux lignes<input data-p="${i}" data-prize="1" value="${p.prizes?.[1]?.label||''}"></label></div><label>Carton plein<input data-p="${i}" data-prize="2" value="${p.prizes?.[2]?.label||''}"></label></div>`).join('')||'<p>Aucune partie.</p>';}
function readProgram(){const s=Loto.state();const parties=JSON.parse(JSON.stringify(s.program?.parties||[]));partiesList.querySelectorAll('input[data-p]').forEach(inp=>{const p=Number(inp.dataset.p);parties[p] ||= {name:'Partie '+(p+1),prizes:[{type:'Ligne',label:''},{type:'Deux lignes',label:''},{type:'Carton plein',label:''}]};if(inp.dataset.f==='name')parties[p].name=inp.value;if(inp.dataset.prize){const pi=Number(inp.dataset.prize);const types=['Ligne','Deux lignes','Carton plein'];parties[p].prizes ||= [];parties[p].prizes[pi]={type:types[pi],label:inp.value};}});return {title:Loto.state().program?.title||'Loto',parties};}
document.getElementById('saveGeneral').onclick=()=>Loto.save({lotoName:lotoName.value||'LOTO SDS',options:{...Loto.state().options,prevalidateSeconds:Number(prevalidate.value||6)}});
document.getElementById('addPartie').onclick=()=>{const s=Loto.state();const program=readProgram();program.parties.push({name:'Partie '+(program.parties.length+1),prizes:[{type:'Ligne',label:''},{type:'Deux lignes',label:''},{type:'Carton plein',label:''}]});Loto.save({program});};
document.getElementById('saveProgram').onclick=()=>Loto.save({program:readProgram(),options:{...Loto.state().options,showLots:showLots.checked}});
document.getElementById('saveBingo').onclick=()=>Loto.save({options:{...Loto.state().options,bingoEnabled:bingoEnabled.checked,showBingo:showBingo.checked}});
document.getElementById('testCardBtn').onclick=async()=>{const n=document.getElementById('testCard').value;const c=await Loto.fetchCard?.(n);document.getElementById('testCardResult').textContent=c?JSON.stringify(c,null,2):'Carton introuvable';};
Loto.onChange(s=>{Loto.pageHeader();lotoName.value=s.lotoName||'LOTO SDS';prevalidate.value=s.options?.prevalidateSeconds||6;showLots.checked=!!s.options?.showLots;bingoEnabled.checked=!!s.options?.bingoEnabled;showBingo.checked=!!s.options?.showBingo;drawParties();});
Loto.ensureSession();
