const page=document.body.dataset.page;const qs=new URLSearchParams(location.search);const CODE=(qs.get('s')||localStorage.getItem('lotoCode')||'DEMO').toUpperCase();localStorage.setItem('lotoCode',CODE);const cfg=window.LOTO_CONFIG||{};let supa=null,state=null,saving=false,voice=null,micAuthorized=false,voiceFirst=null,lastChecked=null;const PREVALID_SECONDS=8;
const $=id=>document.getElementById(id);const game=()=>state.games.find(g=>g.id===state.currentGameId)||state.games[0];
boot();

function checkTeamAccess(){
  if(page==='joueur') return true;
  const pin=String((cfg&&cfg.TEAM_PIN)||'2580');
  if(localStorage.getItem('lotoTeamPinOk')===pin) return true;
  const lock=document.createElement('div');
  lock.className='pin-lock';
  lock.innerHTML=`<div class="pin-box"><h1>LOTO SDS</h1><p>Acces equipe</p><input id="pinInput" type="password" inputmode="numeric" autocomplete="off" placeholder="Code PIN"><button id="pinBtn">Entrer</button><div id="pinError" class="pin-error"></div></div>`;
  document.body.innerHTML='';
  document.body.appendChild(lock);
  const input=document.getElementById('pinInput');
  const btn=document.getElementById('pinBtn');
  const err=document.getElementById('pinError');
  const submit=()=>{if(input.value.trim()===pin){localStorage.setItem('lotoTeamPinOk',pin);location.reload()}else{err.textContent='Code PIN incorrect';input.value='';input.focus()}};
  btn.onclick=submit;
  input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});
  setTimeout(()=>input.focus(),50);
  return false;
}
function logoutTeam(){localStorage.removeItem('lotoTeamPinOk');location.reload()}

async function boot(){if(!checkTeamAccess())return;if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY){alert('config.js non configuré');return}supa=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);buildUi();await loadState();listen();render();setInterval(tick,500)}
function defaultState(){const now=new Date().toISOString();const id='p-'+Date.now();return{code:CODE,title:'Loto Comité des Fêtes',microWanted:false,createdAt:now,updatedAt:now,currentGameId:id,games:[{id,label:'Partie 1',createdAt:now,history:[],pending:null,pendingAt:null,checkedLog:[],publicCards:[]}]} }
async function loadState(){const r=await supa.from('loto_app_sessions').select('state').eq('code',CODE).maybeSingle();if(r.error){alert(r.error.message);return}if(r.data){state=r.data.state;return}state=defaultState();await supa.from('loto_app_sessions').insert({code:CODE,state})}
function listen(){supa.channel('loto-'+CODE).on('postgres_changes',{event:'UPDATE',schema:'public',table:'loto_app_sessions',filter:'code=eq.'+CODE},p=>{state=p.new.state;render();syncMic()}).subscribe()}
async function save(){if(!state||saving)return;saving=true;state.updatedAt=new Date().toISOString();await supa.from('loto_app_sessions').update({state,updated_at:new Date().toISOString()}).eq('code',CODE);saving=false}
function buildUi(){if(page==='public'){for(let n=1;n<=90;n++)$('board').append(numEl(n,false));$('authorizeMic').onclick=authorizeMic}else if(page==='animateur'){for(let n=1;n<=90;n++){const b=numEl(n,true);b.onclick=()=>manualNumber(n);$('remoteBoard').append(b)}$('microBtn').onclick=()=>{state.microWanted=!state.microWanted;save();render()};$('undoBtn').onclick=undoLast;$('errorBtn').onclick=voiceError;$('newGameBtn').onclick=()=>{if(confirm('Créer une nouvelle partie ?'))newGame()};$('resumeLastBtn').onclick=resumeLast;$('saveBtn').onclick=save}else if(page==='commissaire'){for(let n=1;n<=90;n++)$('commissaireBoard').append(numEl(n,false));bindCards()}else if(page==='joueur'){for(let n=1;n<=90;n++)$('playerBoard').append(numEl(n,false))}}
function bindCards(){if(!$('checkBtn'))return;$('checkBtn').onclick=checkCard;$('cardInput').addEventListener('keydown',e=>{if(e.key==='Enter')checkCard()});$('showPublicBtn').onclick=showCardPublic;$('closePublicBtn').onclick=()=>{game().publicCards=[];save()}}
function numEl(n,button){const e=document.createElement(button?'button':'div');e.className='num';e.id=(button?'r':'n')+n;e.textContent=n;return e}
function commitPending(){const g=game();if(g.pending&&!g.history.includes(g.pending)){g.history.push(g.pending)}g.pending=null;g.pendingAt=null}
function setPending(n){const g=game();if(g.history.includes(n))return;commitPending();g.pending=n;g.pendingAt=Date.now();save();render()}
function manualNumber(n){const g=game();if(g.history.includes(n)){if(confirm('Retirer le '+n+' ?')){g.history=g.history.filter(x=>x!==n);if(g.pending===n){g.pending=null;g.pendingAt=null}save();render()}return}setPending(n)}
function tick(){if(!state)return;const g=game();if(g&&g.pending&&Date.now()-g.pendingAt>PREVALID_SECONDS*1000){commitPending();save();render()}}
function undoLast(){const g=game();if(g.pending){g.pending=null;g.pendingAt=null}else{g.history.pop()}save();render()}
function voiceError(){voiceFirst=null;const g=game();if(g.pending){g.pending=null;g.pendingAt=null;save();render()}}
function newGame(){commitPending();const id='p-'+Date.now();state.games.unshift({id,label:'Partie '+(state.games.length+1),createdAt:new Date().toISOString(),history:[],pending:null,pendingAt:null,checkedLog:[],publicCards:[]});state.currentGameId=id;save();render()}
function resumeLast(){state.currentGameId=state.games[0].id;save();render()}
function render(){if(!state)return;const g=game();if(page==='public'){ $('title').textContent='LOTO SDS'; $('sessionInfo').textContent='Session '+CODE+' - '+g.label; renderNumbers(g,false); renderPublicCards(g); renderQrCode(); } if(page==='animateur'){ $('status').textContent='Session '+CODE+' - '+g.label; $('microBtn').textContent=state.microWanted?'MICRO ACTIF':'MICRO INACTIF';$('microBtn').className='mic '+(state.microWanted?'mic-on':'mic-off');$('remoteLast').textContent=lastNumber(g)||'--';$('remotePending').textContent=g.pending||'--';$('remoteCount').textContent=g.history.length;renderNumbers(g,true);renderGames(); } if(page==='commissaire'){ $('status').textContent='Session '+CODE+' - '+g.label; renderNumbers(g,false); if($('commissaireLast')) $('commissaireLast').textContent=g.pending||lastNumber(g)||'--'; } if(page==='joueur'){ $('playerStatus').textContent='Session '+CODE+' - '+g.label; renderNumbers(g,false); if($('playerLast')) $('playerLast').textContent=g.pending||lastNumber(g)||'--'; if($('playerHistory')) $('playerHistory').innerHTML=g.history.map((n,i)=>`<span class="pill">${i+1}. ${n}</span>`).join(''); } }
function renderNumbers(g,remote){const ids=remote?'r':'n';for(let n=1;n<=90;n++){const el=$(ids+n);if(!el)continue;el.className='num';if(g.history.includes(n))el.classList.add('drawn');if(g.pending===n)el.classList.add('pending');if(lastNumber(g)===n)el.classList.add('last')} if(!remote){$('lastNumber').textContent=g.pending||lastNumber(g)||'--';$('pendingLabel').textContent='';$('history').innerHTML=g.history.map((n,i)=>`<span class="pill">${i+1}. ${n}</span>`).join('')}}
function lastNumber(g){return g.history[g.history.length-1]||null}
function renderGames(){if(!$('games'))return;$('games').innerHTML=state.games.map(g=>`<div class="game-row"><span>${g.label}<br><small>${new Date(g.createdAt).toLocaleString('fr-FR')} - ${g.history.length} numéros</small></span><button data-id="${g.id}">Reprendre</button></div>`).join('');$('games').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.currentGameId=b.dataset.id;save();render()})}
function findCard(code){return (typeof CARTONS!=='undefined'?CARTONS:[]).find(c=>String(c[0])===String(code))}
function checkCard(){const code=$('cardInput').value.trim();const c=findCard(code);const g=game();if(!c){$('cardPreview').innerHTML='<p class="miss">Carton introuvable.</p>';return}const nums=c.slice(1);const drawn=[...g.history];if(g.pending)drawn.push(g.pending);const missing=nums.filter(n=>!drawn.includes(n));lastChecked={code,numbers:nums,missing,checkedAt:new Date().toISOString()};g.checkedLog.unshift(lastChecked);$('cardPreview').innerHTML=cardHtml(lastChecked,true);save();renderLog(g)}
function showCardPublic(){if(!lastChecked)return;game().publicCards=[lastChecked];save()}
function renderLog(g){if(!$('checkedLog'))return;$('checkedLog').innerHTML=(g.checkedLog||[]).map(c=>`<div class="log-row"><span>Carton ${c.code}<br><small>${c.missing.length?'Manquants : '+c.missing.join(', '):'VALIDE'}</small></span></div>`).join('')}
function renderQrCode(){const img=$('playerQr');const urlBox=$('playerUrl');if(!img||!urlBox)return;const u=new URL('joueur.html',location.href);u.searchParams.set('s',CODE);urlBox.textContent=u.href;img.src='https://api.qrserver.com/v1/create-qr-code/?size=150x150&data='+encodeURIComponent(u.href)}
function renderPublicCards(g){const box=$('cardOverlay');const inner=$('publicCards');if(!g.publicCards||!g.publicCards.length){box.classList.add('hidden');inner.innerHTML='';return}box.classList.remove('hidden');inner.innerHTML=g.publicCards.map(c=>cardHtml(c,false)).join('<hr>')}
function cardHtml(c,small){const g=game();const all=[...g.history];if(g.pending)all.push(g.pending);return `<div class="card-title">Carton ${c.code}</div><div class="card-grid">${c.numbers.map(n=>`<div class="card-num ${all.includes(n)?'ok':''} ${lastNumber(g)===n||g.pending===n?'last':''}">${n}</div>`).join('')}</div><div class="card-msg ${c.missing.length?'miss':'win'}">${c.missing.length?'Numéros manquants : '+c.missing.join(', '):'CARTON VALIDE'}</div>`}
async function authorizeMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Reconnaissance vocale non disponible. Utiliser Chrome ou Edge.');return}voice=new SR();voice.lang='fr-FR';voice.continuous=true;voice.interimResults=false;voice.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){handleSpeech(e.results[i][0].transcript)}};voice.onend=()=>{if(state&&state.microWanted&&micAuthorized)setTimeout(()=>{try{voice.start()}catch{}},500)};micAuthorized=true;$('authorizeMic').textContent='Micro PC';syncMic()}
function syncMic(){if(page!=='public'||!voice||!micAuthorized)return;const btn=$('authorizeMic');if(state.microWanted){btn.textContent='Micro PC';btn.className='mic mic-on';try{voice.start()}catch{}}else{btn.textContent='Micro PC';btn.className='mic mic-off';try{voice.stop()}catch{}}}
function handleSpeech(text){const t=normalize(text);if(t.includes('fermer affichage carton')){game().publicCards=[];save();return}if(t.includes('annuler dernier')){undoLast();return}if(t.includes('erreur')){voiceError();return}const n=extractNumber(t);if(!n)return;if(voiceFirst===n){voiceFirst=null;setPending(n)}else{voiceFirst=n}}
function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[-']/g,' ')}
function extractNumber(t){const digits=t.match(/\b([1-9]|[1-8][0-9]|90)\b/);if(digits)return Number(digits[1]);const words={un:1,une:1,deux:2,trois:3,quatre:4,cinq:5,six:6,sept:7,huit:8,neuf:9,dix:10,onze:11,douze:12,treize:13,quatorze:14,quinze:15,seize:16,vingt:20,trente:30,quarante:40,cinquante:50,soixante:60};const parts=t.split(/\s+/).filter(Boolean);for(let i=0;i<parts.length;i++){let w=parts[i];if(words[w]){if(w==='vingt'||w==='trente'||w==='quarante'||w==='cinquante'||w==='soixante'){let v=words[w];let n=parts[i+1];if(n==='et')n=parts[i+2];if(words[n]&&words[n]<10)v+=words[n];if(v>=1&&v<=90)return v}return words[w]}if(w==='quatre'&&parts[i+1]==='vingt'){let v=80;let n=parts[i+2];if(words[n]&&words[n]<10)v+=words[n];return v}if(w==='soixante'&&parts[i+1]==='dix')return 70}return null}
