Loto.pageHeader();Loto.protectPage();
const grid=document.getElementById('grid'),last=document.getElementById('last'),history=document.getElementById('history'),qr=document.getElementById('qr'),playerLink=document.getElementById('playerLink'),micBtn=document.getElementById('micBtn'),overlay=document.getElementById('cardOverlay'),lotBox=document.getElementById('lotBox');
function playerUrl(){ return (Loto.C.PLAYER_URL || (location.origin+location.pathname.replace('public.html','joueur.html'))) + '?s=' + encodeURIComponent(Loto.code()); }
function renderCard(card){ if(!card){ overlay.style.display='none'; return; } overlay.style.display='block'; const lines=(card.lignes||[]).map((l,i)=>`<tr><th>Ligne ${i+1}</th>${l.map(n=>`<td style="padding:14px 18px;border:1px solid #ddd;font-size:34px;font-weight:900">${String(n).padStart(2,'0')}</td>`).join('')}</tr>`).join(''); overlay.innerHTML=`<h1 style="font-size:56px;margin:0 0 18px">Carton ${card.numero}</h1><p style="font-size:30px" class="${card.full?'ok':'bad'}">${card.full?'CARTON PLEIN':'Manque : '+(card.missing||[]).join(' - ')}</p><table style="border-collapse:collapse;width:100%;text-align:center">${lines}</table>`; }
function renderLots(s){ const opts=s.options||{}; if(!opts.showLots){lotBox.style.display='none';return;} const p=(s.program?.parties||[])[s.currentPartieIndex||0]; if(!p){lotBox.style.display='none';return;} const prize=(p.prizes||[])[s.currentPrizeIndex||0]; lotBox.style.display='block'; lotBox.innerHTML=`<h3>${p.name||'Partie'}</h3><h2>${prize?.type||''}</h2><p>${prize?.label||''}</p>`; }
Loto.onChange(s=>{ Loto.pageHeader(); last.textContent=Loto.lastNumber(); Loto.renderNumbers(grid); history.innerHTML=(s.drawnNumbers||[]).slice(-20).reverse().map(n=>`<span class="pill">${String(n).padStart(2,'0')}</span>`).join(''); renderCard(s.publicCard); renderLots(s); });
Loto.ensureSession();
const url=playerUrl(); playerLink.textContent=url; QRCode.toCanvas(url,{width:180,margin:1},(err,canvas)=>{ if(!err){ qr.innerHTML=''; qr.appendChild(canvas); }});
micBtn.onclick=()=>LotoVoice.toggle((on)=>{micBtn.textContent=on?'Micro PC actif':'Micro PC';micBtn.className='small '+(on?'red':'green');});
