Loto.pageHeader();Loto.protectPage();
const grid=document.getElementById('grid'),last=document.getElementById('last'),history=document.getElementById('history'),qr=document.getElementById('qr'),playerLink=document.getElementById('playerLink'),micBtn=document.getElementById('micBtn'),overlay=document.getElementById('cardOverlay'),lotBox=document.getElementById('lotBox'),bingoBox=document.getElementById('bingoBox'),publicLotBanner=document.getElementById('publicLotBanner');
function playerUrl(){ return (Loto.C.PLAYER_URL || (location.origin+location.pathname.replace('public.html','joueur.html'))) + '?s=' + encodeURIComponent(Loto.code()); }
function renderCard(card){ if(!card){ overlay.style.display='none'; return; } overlay.style.display='block'; const lines=(card.lignes||[]).map((l,i)=>`<tr><th>Ligne ${i+1}</th>${l.map(n=>`<td style="padding:14px 18px;border:1px solid #ddd;font-size:34px;font-weight:900">${String(n).padStart(2,'0')}</td>`).join('')}</tr>`).join(''); const req=card.requirement||{}; overlay.innerHTML=`<h1 style="font-size:56px;margin:0 0 18px">Carton ${card.numero}</h1><p style="font-size:34px"><b>${req.label||''}</b></p><p style="font-size:34px" class="${card.valid?'ok':'bad'}">${card.valid?'GAIN VALIDE':'NON VALIDE'}</p><p style="font-size:24px">${card.reason||''}</p><table style="border-collapse:collapse;width:100%;text-align:center">${lines}</table>`; }
function renderLots(s){ const opts=s.options||{}; const p=Loto.currentPartie(); const prize=Loto.currentPrize(); if(!opts.showLots||!p||!prize){lotBox.style.display='none';publicLotBanner.textContent='';return;} const total=(s.program?.parties||[]).length; const req=Loto.currentRequirement(); publicLotBanner.innerHTML=`<span>Partie ${(s.currentPartieIndex||0)+1}${total?' / '+total:''}</span><strong>${req.label}</strong><span>${prize.label||'Lot non renseigné'}</span>`; lotBox.style.display='block'; lotBox.innerHTML=`<h3>${p.name||'Partie'}</h3><p class="mode-label">${Loto.gameModeLabel(p)}</p><h2>${req.label}</h2><p>${prize?.label||''}</p>`; }
function renderBingo(s){ if(!s.options?.showBingo || !s.options?.bingoEnabled){bingoBox.style.display='none';return;} bingoBox.style.display='block'; bingoBox.innerHTML=`<h3>Bingo</h3><div class="history">${(s.bingoNumbers||[]).slice(-20).reverse().map(n=>`<span class="pill bingo-pill">${String(n).padStart(2,'0')}</span>`).join('')}</div>`; }
Loto.onChange(s=>{ Loto.pageHeader(); last.textContent=Loto.lastNumber(); Loto.renderNumbers(grid); history.innerHTML=(s.drawnNumbers||[]).slice(-20).reverse().map(n=>`<span class="pill">${String(n).padStart(2,'0')}</span>`).join(''); renderCard(s.publicCard); renderLots(s); renderBingo(s); });
Loto.ensureSession();
const url=playerUrl(); playerLink.textContent=url; QRCode.toCanvas(url,{width:180,margin:1},(err,canvas)=>{ if(!err){ qr.innerHTML=''; qr.appendChild(canvas); }});
micBtn.onclick=()=>LotoVoice.toggle((on)=>{micBtn.textContent=on?'Micro PC actif':'Micro PC';micBtn.className='small '+(on?'red':'green');});
