const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let realtimeChannel=null, refreshTimer=null, soldRows=[], movementRows=[];
function context(){const s=Loto.state();return{id:s.program?.id||s.sessionCode||Loto.code(),title:s.program?.title||s.lotoName||'Loto actif',enabled:!!s.program?.sales_tracking_enabled,voucherEnabled:!!s.program?.validation_voucher_enabled};}
function status(text,good=true){const el=$('saleStatus');el.style.display='block';el.className='notice '+(good?'ok-note':'bad-note');el.textContent=text;}
function scannerUrl(){const u=new URL('scanner-vente.html',location.href);u.searchParams.set('s',Loto.code());return u.href;}
function renderHeader(){const c=context(),el=$('saleLotoInfo');el.className='notice '+(c.enabled?'ok-note':'bad-note');el.innerHTML='<b>Loto actif :</b> '+esc(c.title)+(c.enabled?' · suivi des ventes activé'+(c.voucherEnabled?' · bon de validation obligatoire':' · vente directe'):' · activez le suivi des ventes dans Administration > Loto / lots');const url=scannerUrl();$('saleScannerUrl').textContent=url;const box=$('saleScannerQr');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:url,width:210,height:210,correctLevel:QRCode.CorrectLevel.M});}
function rowCode(r){return r.carton_code||String(r.numero);}
function applyFilter(){const q=$('saleSearch').value.trim().toLowerCase();const sold=soldRows.filter(r=>!q||rowCode(r).toLowerCase().includes(q));$('saleSoldList').innerHTML=sold.length?sold.map(r=>`<div class="saved-row"><div><b>${esc(rowCode(r))}</b><br><span class="muted">Vendu le ${new Date(r.sold_at).toLocaleString('fr-FR')}</span></div><span class="sale-state sold">VENDU</span></div>`).join(''):'<p class="muted">Aucun carton vendu correspondant.</p>';const moves=movementRows.filter(r=>!q||rowCode(r).toLowerCase().includes(q));$('saleHistory').innerHTML=moves.length?moves.map(r=>`<div class="saved-row"><div><b>${r.action==='retour'?'Retour':'Vente'} · ${esc(rowCode(r))}</b><br><span class="muted">${new Date(r.created_at).toLocaleString('fr-FR')}</span></div><span class="sale-state ${r.action==='retour'?'returned':'sold'}">${r.action==='retour'?'RETOUR':'VENTE'}</span></div>`).join(''):'<p class="muted">Aucun mouvement correspondant.</p>';}
async function refresh(){const client=Loto.supabaseClient,c=context();if(!client){status('Supabase non configuré.',false);return;}const [{count:created,error:ce},{data:sales,error:se},{data:moves,error:me}]=await Promise.all([client.from('loto_cartons').select('*',{count:'exact',head:true}).eq('actif',true).eq('origine','Loto by SdS'),client.from('loto_carton_sales').select('numero,carton_code,status,sold_at,updated_at').eq('loto_id',c.id).order('updated_at',{ascending:false}),client.from('loto_carton_movements').select('numero,carton_code,action,created_at').eq('loto_id',c.id).order('created_at',{ascending:false}).limit(250)]);if(ce||se||me){status('Lecture des ventes impossible : '+(ce||se||me).message,false);return;}soldRows=(sales||[]).filter(x=>x.status==='vendu');movementRows=moves||[];const returns=movementRows.filter(x=>x.action==='retour').length;$('saleCreatedCount').textContent=created||0;$('saleSoldCount').textContent=soldRows.length;$('saleAvailableCount').textContent=Math.max(0,(created||0)-soldRows.length);$('saleReturnCount').textContent=returns;applyFilter();}
async function releaseAll(){const c=context(),client=Loto.supabaseClient;if(!c.enabled){status('Le suivi des ventes n’est pas activé pour ce loto.',false);return;}if(!confirm('Libérer tous les cartons vendus pour ce loto ?\n\nLes statistiques et l’historique seront conservés.'))return;const now=new Date().toISOString();const {data:current,error:re}=await client.from('loto_carton_sales').select('numero,carton_code').eq('loto_id',c.id).eq('status','vendu');if(re){status('Action impossible : '+re.message,false);return;}if(!current?.length){status('Aucun carton vendu à libérer.',true);return;}const nums=current.map(x=>x.numero);const {error:e1}=await client.from('loto_carton_sales').update({status:'disponible',updated_at:now}).eq('loto_id',c.id).eq('status','vendu');if(e1){status('Action impossible : '+e1.message,false);return;}await client.from('loto_cartons').update({status:'disponible',sale_loto_id:null,sold_at:null,sold_by:null,updated_at:now}).in('numero',nums);await client.from('loto_carton_movements').insert(current.map(x=>({loto_id:c.id,loto_title:c.title,numero:x.numero,carton_code:x.carton_code,action:'retour',source:'cloture',created_at:now})));status(current.length+' carton(s) remis disponibles. Historique conservé.',true);await refresh();}
function subscribe(){const client=Loto.supabaseClient,c=context();if(!client)return;if(realtimeChannel)client.removeChannel(realtimeChannel);realtimeChannel=client.channel('sales_dashboard_'+c.id).on('postgres_changes',{event:'*',schema:'public',table:'loto_carton_sales',filter:'loto_id=eq.'+c.id},scheduleRefresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'loto_carton_movements',filter:'loto_id=eq.'+c.id},scheduleRefresh).subscribe();}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,200);}
$('saleRefresh').onclick=refresh;$('releaseAllCards').onclick=releaseAll;$('saleSearch').addEventListener('input',applyFilter);window.addEventListener('pagehide',()=>{if(realtimeChannel&&Loto.supabaseClient)Loto.supabaseClient.removeChannel(realtimeChannel);});Loto.onChange(()=>{Loto.pageHeader();renderHeader();});Loto.ensureSession().then(()=>{Loto.pageHeader();renderHeader();refresh();subscribe();});Loto.protectPage();
